listItems= '''CheckIfNotExistWithType.js
getDbDataSimple.js
jquery.fontselect.min.js
DragnDropQR.js
ResultsOfExist.js
EmpyFieldsHtmlCodehiddenReverced.js
getFileName.js
UnhideScrollAndImg.js
CheckIfNameExists.js
getNameOfLocations.js
returnFromRunReturnFromSameFileInside.js
LoadMultipleFiles.js
gotResultsRemove.js
checkPathEChange.js
SelectText.js
CancelFunction.js
AlteredOrOpenedDocument.js
UnhideScrollAndImg2.js
fileAlreadyExists.js
GJDcheckIfNameNOTexists.js
placeValuesInFileReturn.js
GetJobDataJason.js
LoadMutipleFileJason.js
GetImageCoordinates5.js
gotResultsAdd.js
DragnDropMidWETP.js
popper.min.js
LMFAddInfoExcelResults.js
CurrentWorkingPathFunc.js
AddtoTablePromise.js
getDbDataPPPPPPPPPPPPPPP.js
gotResults.js
dragAndDropWETP.js
DragnDropMidWETP0.js
DelTypeJobNameReload.js
GetImageCoordinates4CheckClick.js
DragnDropMid0.js
DragnDropMidQR0.js
CreateImageWithMarkerStep5Return.js
GetImageCoordinates3.js
CreateImageWithMarkerReturn.js
dragAndDropSFIF.js
popperImport.js
LMFNotValidFileNames.js
RunPythonFileZZZZZZ.js
DragnDropMidSFIF.js
LoadSingleQRFile.js
getDbData.js
DragnDropMid.js
LMFAddInfoExcelFunction.js
getDatafillName.js
IndexgetDatabaseData.js
TypeJobName.js
getLocationSaved.js
getRowNumberInTableByClass.js
RerunReturnFromSameFileInside.js
JoinPdfschooseFolder.js
placeInHTML2Id.js
GetJobDataStart.js
insertIntoDatabase.js
runReturnFromSameFileInside.js
RunPythonFileWWWWWWWWWW.js
OperationComplete.js
GJDcheckIfChecked.js
MyDocumentsDatabasePath.js
ProgressBarGotResults.js
PythonOrdToString.js
loadMultipleFileResults.js
LMFAddInfoExcel.js
OPFSelectImageFile.js
bootstrap.js
LMF_AIE_AlteredOrOpenedDocument.js
DragnDrop2.js
GetOldWordStamp.js
CreateImageWithMarkerStep5Return2.js
validate.js
AsyncActionFunction.js
LMFItemCheckedHTML.js
FindJobExelLocations.js
LocationSavedSub.js
LocationSaved.js
OPFSelectImageFile3.js
addInforToTheDocumentHTMLcall.js
RemoveGotResultsOnHtml.js
DelCheckIfChecked.js
gotResultsRemove2.js
jquery.js
DeleteTempFIlesFromApp.js
LMFAddInfoSave.js
DeleteFromDatabase.js
checkIfNameNOTexists.js
bootstrap.min.js
AddToTable.js
AddJquery.js
fontSelect.js
placeValuesInFile.js
jqueryImport.js
checkPathEChange2.js
DragnDropMidQR.js
Cancel.js
UnhideScrollEvent.js
OperationCompleteAtHtml.js
bootstrap.bundle.min.js
OKDeleteFromDatabase.js
jquery-3.6.1.min.js
getResultsList.js
LMFchooseFolder.js
EventListeners.js
AddToDatabaseReturn.js
checkIfAllInputsFilled.js
DragnDrop.js
DelOptionsForIfExists.js
jquery.fontselect.js
continuationLoadMultipleFilesFromDatabase.js
GetImageCoordinates.js
RerunReturnFromSameFileInsideFunction.js
LMFcheckIfNameNOTexists.js
spinnerStartup.js
OPFSelectImageFile4.js
GetJobData.js
indexFunctions.js
placeInHTMLId.js
RunPythonFile.js
ImageJoinPdfschooseFolder.js
GetImageCoordinates4.js
RunPythonFileZZZZZZZZZZZZZZZUUUUUUUUUU.js
GetImageCoordinates2.js
OPFFolderSaveLocation.js
LMFcheckIfChecked.js
getRealdatafillName.js
'''

ListOfIems2 =listItems.split(".")

setOfItems = set(ListOfIems2)

print(setOfItems)